# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source "https://github.com/cyber-z/public-fox-ios-sdk.git"

target 'FOXExtension' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FOXExtension
  pod "foxSdk"

end
